name: Run Tests Based on API Selection

on:
  workflow_dispatch:
    inputs:
      selected-api:
        description: 'Select API version'
        required: true
        default: 'API1.0'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirements.txt') }}

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirements.txt 

      - name: Run Tests
        run: |
          if (${env:selected-api} -eq "API1.0") {
            Write-Host "Running tests for API1.0"
            python -m robot --outputdir reports -x junit-report.xml --include Test1 tests/Group1.robot
          }
          elseif (${env:selected-api} -eq "API2.0") {
            Write-Host "Running tests for API2.0"
            python -m robot --outputdir reports -x junit-report.xml --include Test2 tests/Group1.robot
          }
          else {
            Write-Host "Invalid API selection: ${env:selected-api}"
            exit 1
          }

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: robot-test-results
          path: reports
