name: Run Tests Based on API Selection

on:
  workflow_dispatch:
    inputs:
      selected-api:
        description: 'Select API version'
        required: true
        default: 'API1.0'

jobs:
  test:
    runs-on: windows-latest

    steps:
      - name: Checkout repository
        uses: actions/checkout@v2

      - uses: actions/cache@v2
        id: cache
        with:
          path: ~/.cache/pip
          key: ${{ runner.os }}-pip-${{ hashFiles('**/requirement.txt') }}

      - name: Install pip dependencies
        run: |
          python -m pip install --upgrade pip
          python -m pip install -r requirement.txt 

      - name: Debug API Value
        run: |
          echo "Selected API: ${{ github.event.inputs.selected-api }}"

      - name: Run Tests
        run: |
          if [[ "${{ github.event.inputs.selected-api }}" == "API1.0" ]]; then
            echo "Running tests for API1.0"
            python -m robot --outputdir reports -x junit-report.xml --include Test1 tests/Group1.robot
          elif [[ "${{ github.event.inputs.selected-api }}" == "API2.0" ]]; then
            echo "Running tests for API2.0"
            python -m robot --outputdir reports -x junit-report.xml --include Test2 tests/Group1.robot
          else
            echo "Invalid API selection: ${{ github.event.inputs.selected-api }}"
            exit 1
          fi

      - name: Publish test results
        uses: actions/upload-artifact@v2
        with:
          name: robot-test-results
          path: reports
