name: Adding Bots Job
on:
  workflow_dispatch:
defaults:
  run:
    shell: cmd
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set up Python
          uses: actions/setup-python@v2
          with:
            python-version: 3.8
      - name: Change directory and run Python script
          run: |
            cd C:\Users\Professional\PycharmProjects\RobotFramework\scripts
            python test.py
