name: Adding Bots Job
on:
  workflow_dispatch:
defaults:
  run:
    shell: cmd
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Checkout code
        uses: actions/checkout@v2
      - name: Set working directory
        run: |
          cd C:\Users\Professional\PycharmProjects\RobotFramework\scripts
      - name: Run Python script
        run: python test.py
