name: Adding Bots Job
on:
  workflow_dispatch:
defaults:
  run:
    shell: bash
jobs:
  build:
    runs-on: windows-latest
    steps:
      - name: Display working directory
        run: |
          pwd
          echo $GITHAB_SHA

      - name: Checkout code
        uses: actions/checkout@v2

      - name: Set working directory
        run: |
          cd /c/Users/Professional/PycharmProjects/RobotFramework/scripts

      - name: Display working directory
        run: |
          pwd
          echo $GITHAB_SHA

      - name: Run Python script
        run: python test.py
